# Generated by Django 4.0.2 on 2026-03-10 00:00

from django.db import migrations, models


def seed_resource_sections(apps, schema_editor):
    ResourceSection = apps.get_model("posts", "ResourceSection")
    ResourceGroup = apps.get_model("posts", "ResourceGroup")

    section_specs = [
        {
            "title": "Tai lieu tieng Nhat",
            "slug": "tai-lieu-tieng-nhat",
            "description": "Tong hop link nghe, doc hieu, tu vung, ngu phap, kanji theo trinh do.",
            "display_order": 1,
            "groups": ["N5", "N4", "N3", "N2", "N1", "Khac"],
        },
        {
            "title": "SRC Game",
            "slug": "src-game",
            "description": "Moi nhom co the la ten SRC, ben trong them cac link can quan ly.",
            "display_order": 2,
            "groups": ["SRC mau"],
        },
        {
            "title": "Du lich",
            "slug": "du-lich",
            "description": "Luu cac link tham khao, lich trinh va tai nguyen du lich.",
            "display_order": 3,
            "groups": ["Dia diem goi y"],
        },
    ]

    for section_spec in section_specs:
        groups = section_spec.pop("groups")
        section, _ = ResourceSection.objects.get_or_create(
            slug=section_spec["slug"],
            defaults=section_spec,
        )
        for index, group_title in enumerate(groups, start=1):
            ResourceGroup.objects.get_or_create(
                section=section,
                title=group_title,
                defaults={"display_order": index},
            )


def unseed_resource_sections(apps, schema_editor):
    ResourceSection = apps.get_model("posts", "ResourceSection")
    ResourceSection.objects.filter(
        slug__in=["tai-lieu-tieng-nhat", "src-game", "du-lich"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_category_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResourceGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("section", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="groups", to="posts.resourcesection")),
            ],
            options={
                "ordering": ["display_order", "title"],
                "unique_together": {("section", "title")},
            },
        ),
        migrations.CreateModel(
            name="ResourceLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("url", models.URLField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("group", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="links", to="posts.resourcegroup")),
            ],
            options={
                "ordering": ["display_order", "title"],
                "unique_together": {("group", "title")},
            },
        ),
        migrations.RunPython(seed_resource_sections, unseed_resource_sections),
    ]
