# Generated by Django 4.0.2 on 2026-03-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_resourcesection_resourcegroup_resourcelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcelink",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="resourcelink",
            name="document",
            field=models.FileField(blank=True, upload_to="resources/files/"),
        ),
    ]
